  version: '3'
  services:
    homeassistant:
      container_name: homeassistant
      image: homeassistant/raspberrypi4-homeassistant
      volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /config/hass:/config
      - /config/hass:/config
      restart: unless-stopped
      network_mode: host
      # user: 1000:100
      depends_on:
      - deconz
      devices:
      - /dev/zwave:/dev/zwave

    deconz:
      container_name: deconz 
      image: marthoc/deconz
      volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/deconz:/root/.local/share/dresden-elektronik/deCONZ
      devices:
      - /dev/ttyAMA0
      - /dev/ttyUSB0
      restart: unless-stopped
      network_mode: host

    influxdb:
      container_name: influxdb
      image: arm32v7/influxdb:1.8
      restart: unless-stopped
      network_mode: host
      volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config/influx:/var/lib/influxdb
